import { Command } from "commander"
import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  readdirSync,
  copyFileSync,
  statSync,
} from "fs"
import { join, basename } from "path"
import { resolveWorkspace } from "../lib/workspace.js"
import { printOutput, printError, printWarn, type OutputFormat } from "../lib/output.js"

export interface SyncResult {
  copied: string[]
  skipped: string[]
  created: string[]
}

const IDENTITY_FILES = ["SOUL.md", "USER.md", "IDENTITY.md", "MEMORY.md", "AGENTS.md", "TOOLS.md"]

export function syncFromWorkspace(srcDir: string, destDir: string): SyncResult {
  const result: SyncResult = { copied: [], skipped: [], created: [] }

  mkdirSync(destDir, { recursive: true })

  // Copy identity files
  for (const file of IDENTITY_FILES) {
    const src = join(srcDir, file)
    if (existsSync(src)) {
      const dest = join(destDir, file)
      copyFileSync(src, dest)
      result.copied.push(file)
    } else {
      result.skipped.push(file)
    }
  }

  // Copy memory/ directory
  const memSrc = join(srcDir, "memory")
  if (existsSync(memSrc) && statSync(memSrc).isDirectory()) {
    const memDest = join(destDir, "memory")
    mkdirSync(memDest, { recursive: true })
    const files = readdirSync(memSrc)
    for (const f of files) {
      if (f.endsWith(".md")) {
        copyFileSync(join(memSrc, f), join(memDest, f))
        result.copied.push(`memory/${f}`)
      }
    }
  }

  // Create TOOLS-ADAPTATION-NOTES.md
  const notesPath = join(destDir, "TOOLS-ADAPTATION-NOTES.md")
  const notes = `# TOOLS Adaptation Notes

This workspace was synced from an OpenClaw workspace.
Some configuration in TOOLS.md is specific to OpenClaw and needs manual adaptation for GeminiClaw.

## Items to Review

### OpenClaw-specific paths
- Gateway port, token, and control UI URL are OpenClaw-specific — update for GeminiClaw
- \`~/.openclaw/skills/\` paths — GeminiClaw uses \`skills/\` in project root
- sandboxai Cookie configuration — not applicable to GeminiClaw

### GeminiClaw equivalents
- Config: \`config.yaml\` in project root (or \`GC_CONFIG\` env var)
- Skills: \`skills/\` directory, managed via \`gc skill\` commands
- Workspace: \`.workspace/\` directory (configurable via \`workspace.dir\` in config.yaml)

### Recommended next steps
1. Review TOOLS.md and remove/update OpenClaw-specific sections
2. Run \`gc status\` to verify your environment
3. Run \`gc skill list\` to see available capabilities

_Generated by \`gc sync from\` on ${new Date().toISOString()}_
`
  writeFileSync(notesPath, notes, "utf-8")
  result.created.push("TOOLS-ADAPTATION-NOTES.md")

  return result
}

export function registerSyncCommand(program: Command): void {
  const sync = program
    .command("sync")
    .description(
      `Sync identity and memory from another workspace

WHAT
  Copies identity files (SOUL.md, USER.md, IDENTITY.md, MEMORY.md, AGENTS.md, TOOLS.md)
  and daily memory files from a source workspace into this GeminiClaw workspace.
  Also generates TOOLS-ADAPTATION-NOTES.md to flag OpenClaw-specific config.

WHEN (agent guidance)
  Run this once when bootstrapping a new GeminiClaw instance from an OpenClaw workspace.
  Run this to refresh memory after a long gap.
  Do NOT run this on a live workspace without reviewing what will be overwritten.

OUTPUT
  Human: summary of copied/skipped files
  JSON:  { copied: string[], skipped: string[], created: string[] }`
    )

  sync
    .command("from <source-path>")
    .description("Sync from OpenClaw workspace directory (e.g. ~/.openclaw/workspace)")
    .option("--json", "Output as JSON")
    .option("--dry-run", "Show what would be copied without actually copying")
    .action((sourcePath, opts) => {
      const format: OutputFormat = opts.json ? "json" : "human"
      const expandedPath = sourcePath.replace(/^~/, process.env.HOME ?? "~")

      if (!existsSync(expandedPath)) {
        printError(`Source path not found: ${expandedPath}`, format)
        return
      }

      try {
        const ws = resolveWorkspace()
        const destDir = ws.root

        if (opts.dryRun) {
          const lines = [`🔍 Dry run — would sync from: ${expandedPath}`, `   → destination: ${destDir}`, ""]
          for (const file of IDENTITY_FILES) {
            const src = join(expandedPath, file)
            lines.push(`  ${existsSync(src) ? "✅ would copy" : "⚠️  not found"}: ${file}`)
          }
          const memSrc = join(expandedPath, "memory")
          if (existsSync(memSrc)) {
            const count = readdirSync(memSrc).filter((f) => f.endsWith(".md")).length
            lines.push(`  ✅ would copy: memory/ (${count} files)`)
          }
          lines.push(`  ✅ would create: TOOLS-ADAPTATION-NOTES.md`)
          printOutput({ dryRun: true, source: expandedPath, dest: destDir }, lines.join("\n"), format)
          return
        }

        const result = syncFromWorkspace(expandedPath, destDir)

        const humanLines = [
          `✅ Sync complete`,
          `   Source: ${expandedPath}`,
          `   Destination: ${destDir}`,
          "",
          `Copied (${result.copied.length}):`,
          ...result.copied.map((f) => `  ✅ ${f}`),
        ]
        if (result.skipped.length > 0) {
          humanLines.push(`\nSkipped (${result.skipped.length}) — not found in source:`)
          humanLines.push(...result.skipped.map((f) => `  ⚠️  ${f}`))
        }
        if (result.created.length > 0) {
          humanLines.push(`\nCreated:`)
          humanLines.push(...result.created.map((f) => `  📝 ${f}`))
        }
        humanLines.push(
          "",
          "Next steps:",
          "  • Review TOOLS-ADAPTATION-NOTES.md for OpenClaw-specific items",
          "  • Run `gc status` to verify",
          "  • Run `gc identity show` to confirm identity files look correct",
        )

        printOutput(result, humanLines.join("\n"), format)
      } catch (e) {
        printError(String(e), format)
      }
    })
}
